# Generated by Django 4.1 on 2022-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.dirtyapronrecipes.com/recipe/cooked-rice-vermicelli-noodles/', max_length=500),
        ),
    ]
