# Generated by Django 4.1 on 2022-08-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAQWqABN-gmjy8EvyamtBSOSUBQgjPndO1QqZTPVai&s', max_length=500),
        ),
    ]
